import { describe, it } from "vitest";
import assert from "node:assert/strict";
import { facetEvidence, descriptionVector, vectorCosine } from "../src/server/recommendation/review/evidence";
import { referenceSimilarity } from "../src/server/recommendation/review/referenceSimilarity";
import { scoreReviewItem } from "../src/server/recommendation/review/score";
import { reciprocalRankFusion } from "../src/server/recommendation/review/fusion";
import { fuseSemanticSignals } from "../src/server/recommendation/review/semanticSignals";
import { diversifyFinalSlate } from "../src/server/recommendation/review/finalSlate";
import { defaultWeights, featureKeys, type ReviewItem, type RankingFeatures, type ReviewFacet } from "../src/server/recommendation/review/types";
import { scoreLinear, fitPairwiseModel, validateModel } from "../src/server/recommendation/review/linearModel";
const item = (overrides: Partial<ReviewItem> = {}): ReviewItem => ({ id: "one", title: "Untitled", genres: [], mediaType: "movie", ratings: {}, availabilityGroup: "available_in_plex", ...overrides });
const features = (overrides: Partial<RankingFeatures> = {}): RankingFeatures => ({ query: 50, semantic: 50, mood: 50, reference: 50, preference: 50, feedback: 50, availability: 50, quality: 50, friction: 50, ...overrides });
const facet = (term: string, polarity: ReviewFacet["polarity"] = "prefer"): ReviewFacet => ({ term, polarity, source: "explicit" });
const score = (value: ReviewItem, facets: ReviewFacet[] = []) => scoreReviewItem(value, { facets, softGenres: [], positiveQuery: "" });
describe("empty evidence", () => {
  it("does not turn film-by credits into mood evidence", () => assert.equal(facetEvidence({ summary: "A film by Gentle Warm.", genres: [] }, "gentle").polarity, "unknown"));
  it("does not treat an empty facet as affirmative evidence", () => assert.equal(facetEvidence({ summary: "A warm story.", genres: [] }, "  ").polarity, "unknown"));
});
describe("confidence-bearing evidence", () => {
  it("does not treat a title as mood evidence", () => assert.equal(facetEvidence(item({ title: "Quiet Gentle Calm" }), "calm").polarity, "unknown"));
  it("does not infer comfort from animation", () => assert.equal(facetEvidence(item({ genres: ["Animation"] }), "cozy").polarity, "unknown"));
  it("does not infer intensity from maturity classification", () => assert.equal(facetEvidence(item({ contentRating: "TV-MA" }), "intense").polarity, "unknown"));
  it("preserves explicit visual-dark compounds", () => {
    const result = scoreReviewItem(item({ summary: "A candlelit noir story." }), { facets: [facet("visually"), facet("dark")], softGenres: [], positiveQuery: "visually dark movie" });
    assert.ok(result.features.mood > 50);
  });
  it("keeps a genre prior weaker than direct evidence", () => assert.ok(facetEvidence(item({ genres: ["Comedy"] }), "funny").confidence < facetEvidence(item({ summary: "A funny, gentle story." }), "funny").confidence));
  it("does not use genre inference for hard descriptive rejection", () => assert.equal(score(item({ genres: ["Comedy"] }), [facet("funny", "avoid")]).rejected, false));
  it("rejects affirmative descriptive evidence of an explicit avoidance", () => assert.equal(score(item({ summary: "A scary and violent story." }), [facet("scary", "avoid")]).rejected, true));
  it("does not reject degree preferences", () => assert.equal(score(item({ summary: "A scary story." }), [facet("scary", "reduce")]).rejected, false));
  it("degree penalties remain softer than a direct preference", () => assert.ok(score(item({ summary: "A scary story." }), [facet("scary", "reduce")]).features.mood > 0));
  it("missing aesthetic evidence is unknown, not disqualification", () => { const result = score(item(), [facet("visually dark")]); assert.equal(result.rejected, false); assert.equal(result.features.mood, 50); });
  it("honours direct descriptive negation", () => assert.equal(facetEvidence(item({ summary: "An offbeat story without scary scenes." }), "scary").polarity, "negative"));
  it("does not mistake not-only for negation", () => assert.equal(facetEvidence(item({ summary: "Not only scary but moving." }), "scary").polarity, "positive"));
  it("checks each occurrence rather than globally masking a word", () => assert.equal(facetEvidence(item({ summary: "Not scary at first, but later deeply scary." }), "scary").polarity, "positive"));
  it("keeps phrase matching on word boundaries", () => assert.equal(facetEvidence(item({ summary: "A warmth-driven story about a lightbulb." }), "warm").polarity, "unknown"));
  it("strips credit boilerplate from evidence", () => assert.equal(facetEvidence(item({ summary: "Directed by Gentle Calm. A city adventure." }), "gentle").polarity, "unknown"));
  it("does not convert unknown mood into reassuring prose", () => assert.match(score(item(), [facet("cozy")]).explanation, /not established/));
  it("does not duplicate mood votes for repeated identical facets", () => assert.equal(score(item({ summary: "A gentle story." }), [facet("gentle")]).score, score(item({ summary: "A gentle story." }), [facet("gentle"), facet("gentle")]).score));
  it("mixed intent does not fabricate a strong mood preference", () => assert.equal(score(item({ summary: "A scary story." }), [facet("scary", "mixed")]).features.mood, 50));
  it("classification alone does not change adult viewing fit", () => assert.equal(score(item({ contentRating: "PG" })).score, score(item({ contentRating: "R" })).score));
  it("duration does not invent TV episode commitment", () => { const result = scoreReviewItem(item({ mediaType: "tv", runtimeMinutes: 20 }), { facets: [], softGenres: [], positiveQuery: "short series" }); assert.equal(result.features.friction, 50); });
  it("explicit short-movie intent uses movie duration", () => { const result = scoreReviewItem(item({ runtimeMinutes: 80 }), { facets: [], softGenres: [], positiveQuery: "short movie" }); assert.equal(result.features.friction, 85); });
});
describe("direct reference similarity", () => {
  it("compares descriptions rather than names", () => assert.equal(vectorCosine(descriptionVector(item({ title: "same" })), descriptionVector(item({ title: "same" }))), undefined));
  it("recognises direct descriptive similarity", () => assert.ok(referenceSimilarity(item({ summary: "A gentle quiet journey through a rural village." }), item({ summary: "A gentle quiet journey through a rural village." })).similarity! > 0.99));
  it("missing reference evidence is unknown", () => assert.equal(referenceSimilarity(item(), item()).similarity, undefined));
  it("does not replace an unsupported requested aspect with plot", () => assert.equal(referenceSimilarity(item({ summary: "A person visits the city." }), item({ summary: "A person visits the city." }), ["pacing"]).similarity, undefined));
  it("honours an explicit aspect instead of plot overlap", () => {
    const ref = item({ summary: "A gentle quiet voyage through space." });
    const tone = item({ summary: "A gentle quiet story about a rural baker." });
    const plot = item({ summary: "A bleak violent voyage through space." });
    assert.ok(referenceSimilarity(ref, tone, ["tone"]).similarity! > referenceSimilarity(ref, plot, ["tone"]).similarity!);
  });
  it("genre labels cannot manufacture reference-aspect evidence", () => assert.equal(referenceSimilarity(item({ genres: ["Comedy"] }), item({ genres: ["Comedy"] }), ["humour"]).similarity, undefined));
  it("reference similarity is symmetric", () => { const a = item({ summary: "A calm rural story with friendship." }), b = item({ summary: "A calm space story with music." }); assert.equal(referenceSimilarity(a, b).similarity, referenceSimilarity(b, a).similarity); });
  it("does not give the reference itself a near-perfect reference score", () => assert.equal(scoreReviewItem(item(), { facets: [], softGenres: [], positiveQuery: "", reference: item() }).features.reference, 20));
});
describe("retrieval and signal fusion", () => {
  const channels = [{ name: "lexical", ids: ["a", "b", "c"] }, { name: "semantic", ids: ["c", "b", "d"] }];
  it("uses evidence from multiple retrieval channels", () => assert.ok(reciprocalRankFusion(channels, 4).indexOf("b") < reciprocalRankFusion(channels, 4).indexOf("d")));
  it("is invariant to channel order", () => assert.deepEqual(reciprocalRankFusion(channels, 4), reciprocalRankFusion([...channels].reverse(), 4)));
  it("deduplicates within a channel", () => assert.deepEqual(reciprocalRankFusion([{ name: "a", ids: ["x", "x", "y"] }], 5), ["x", "y"]));
  it("excludes hidden candidates before the limit", () => assert.deepEqual(reciprocalRankFusion([{ name: "a", ids: ["x", "y"] }], 1, { excludedIds: new Set(["x"]) }), ["y"]));
  it("protects reference IDs without duplicates", () => assert.deepEqual(reciprocalRankFusion(channels, 2, { protectedIds: ["d", "d"] })[0], "d"));
  it("cannot protect a hidden item into results", () => assert.deepEqual(reciprocalRankFusion([], 2, { protectedIds: ["x"], excludedIds: new Set(["x"]) }), []));
  it("handles zero limits", () => assert.deepEqual(reciprocalRankFusion(channels, 0), []));
  it("rejects duplicate channel names", () => assert.throws(() => reciprocalRankFusion([channels[0], channels[0]], 5)));
  it("rejects invalid budgets", () => assert.throws(() => reciprocalRankFusion(channels, -1)));
  it("zero channel weight contributes no candidates", () => assert.deepEqual(reciprocalRankFusion([{ name: "off", ids: ["x"], weight: 0 }], 5), []));
  it("ties in semantic signals remain equal", () => { const result = fuseSemanticSignals([new Map([["a", 0.5], ["b", 0.5]])]); assert.equal(result.get("a"), result.get("b")); });
  it("does not turn zero similarity into positive rank evidence", () => assert.equal(fuseSemanticSignals([new Map([["a", 0], ["b", -0.5]])]).size, 0));
  it("does not compare unrelated raw cosine scales", () => assert.deepEqual(fuseSemanticSignals([new Map([["a", 0.2], ["b", 0.1]])]), fuseSemanticSignals([new Map([["a", 20], ["b", 10]])])));
  it("keeps fused utilities bounded", () => assert.ok([...fuseSemanticSignals([new Map([["a", 99]]), new Map([["a", 0.01]])]).values()].every((value) => value >= 0 && value <= 100)));
});
describe("learnable ranking utilities", () => {
  const row = { groupId: "training-one", better: features({ mood: 100, quality: 0 }), worse: features({ mood: 0, quality: 100 }) };
  it("default weights sum to one", () => assert.ok(Math.abs(Object.values(defaultWeights).reduce((sum, value) => sum + value, 0) - 1) < 1e-10));
  it("contributions exactly reconstruct score", () => { const result = scoreLinear(features()); assert.equal(result.score, result.contributions.reduce((sum, value) => sum + value.contribution, 0)); });
  it("learns the expressed preference direction", () => assert.ok(fitPairwiseModel([row]).weights.mood > defaultWeights.mood));
  it("learned weights remain non-negative and sum to one", () => { const model = fitPairwiseModel([row]); assert.ok(featureKeys.every((key) => model.weights[key] >= 0)); assert.ok(Math.abs(Object.values(model.weights).reduce((sum, value) => sum + value, 0) - 1) < 1e-8); });
  it("training is independent of row order", () => { const other = { ...row, groupId: "training-two" }; assert.deepEqual(fitPairwiseModel([row, other]), fitPairwiseModel([other, row])); });
  it("retains group-level provenance", () => assert.deepEqual(fitPairwiseModel([row, row]).trainingGroupIds, ["training-one"]));
  it("rejects NaN feature input", () => assert.throws(() => scoreLinear(features({ mood: NaN }))));
  it("rejects out-of-range features", () => assert.throws(() => scoreLinear(features({ mood: 101 }))));
  it("rejects incompatible feature versions", () => assert.throws(() => validateModel({ ...fitPairwiseModel([row]), featureVersion: "wrong" } as never)));
  it("does not trust malformed models", () => assert.throws(() => validateModel({} as never)));
  it("rejects unbounded training work", () => assert.throws(() => fitPairwiseModel([row], { epochs: 1001 })));
  it("rejects empty training data", () => assert.throws(() => fitPairwiseModel([])));
});
describe("final-slate presentation", () => {
  const items = Array.from({ length: 20 }, (_, index) => item({ id: String(index), title: String(index), summary: index < 10 ? "A gentle quiet story." : "A bleak intense story." }));
  it("preserves membership and uniqueness", () => assert.deepEqual(diversifyFinalSlate(items).map((entry) => entry.id).sort(), items.map((entry) => entry.id).sort()));
  it("protects the authoritative first three positions", () => assert.deepEqual(diversifyFinalSlate(items).slice(0, 3), items.slice(0, 3)));
  it("uses final order rather than stale score fields", () => { const scored = items.map((entry, index) => ({ ...entry, score: index * 5 })); assert.deepEqual(diversifyFinalSlate(scored, { lambda: 1 }).map((entry) => entry.id), items.map((entry) => entry.id)); });
  it("bounds promotion and demotion", () => { const result = diversifyFinalSlate(items, { lambda: 0.1, maximumRankDisplacement: 3 }); result.forEach((entry, index) => assert.ok(Math.abs(items.findIndex((old) => old.id === entry.id) - index) <= 3)); });
  it("unknown metadata earns no novelty bonus", () => { const unknown = items.map((entry) => ({ ...entry, summary: undefined })); assert.deepEqual(diversifyFinalSlate(unknown), unknown); });
  it("preserves the tail outside the pool", () => assert.deepEqual(diversifyFinalSlate(items, { poolSize: 10 }).slice(10), items.slice(10)));
  it("does not mutate the input", () => { const before = JSON.stringify(items); diversifyFinalSlate(items); assert.equal(JSON.stringify(items), before); });
  it("rejects duplicate item IDs", () => assert.throws(() => diversifyFinalSlate([items[0], items[0]])));
  it("handles small slates", () => assert.deepEqual(diversifyFinalSlate(items.slice(0, 2)), items.slice(0, 2)));
});
